apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cq2f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cq2f
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cq2f
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cq2f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cq2f
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xeal-tenant/rhtap-demo-app/hacbs-test-project-cq2f@sha256:6e0f08443218d8412579f3cebbe8b9861b8b6bd673e153781ee43c9fb25de6ac
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
